### ISSUE TITLE
Having trouble patching

### ISSUE THREAD

**Issue by user18081972** [AFriendlyIrin/SMT-text-editing#1]
Hi, I tried many different things, but I can't seem to apply the patch correctly. When I boot the patched ROM the game is still in Japanese.
Could you provide some patch instructions?

**Patch applied:**
- smt2eQOL_v1.06; smt2-alt-races.ips. 

**IPS patchers tried:**
- Flips IPS patcher v1.31
- https://www.marcrobledo.com/RomPatcher.js/

**Roms tried:**
- Name: Shin Megami Tensei II (Japan).sfc
Size: 2097152 bytes (2048 KiB)
SHA1: c87207bb39edee9009a97d6cb0a8026df668d6b8

- Name: Shin Megami Tensei II (Japan) (Rev 1).sfc
Size: 2097152 bytes (2048 KiB)
SHA1: 5df931d1b2fa2f4d28036c2641a043490e9a8cdf

- Name: Shin Megami Tensei II (Japan) (Rev 2).sfc
Size: 2097152 bytes (2048 KiB)
SHA1: 84bb8a37b2575762d825d820d76175071bee1ca2

**Comment by AFriendlyIrin** [comment]
You need to apply the patch after the English translation patch.
